# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodingTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'SDWebImage'
pod 'SwiftyJSON', '~> 4.0'
pod 'AlamofireObjectMapper', '~> 5.2'


  # Pods for CodingTest

  target 'CodingTestUITests' do
    # Pods for testing
  end

end
